### PR TITLE
Fix chunk unload packets not sending & send packets in a more efficient order on player join

### LINKED ISSUE #70: Sending duplicate chunks to player
Testing [lines 135-149 in `ThreadedAnvilStorageMixin`](https://github.com/astei/krypton/blob/d24cb7e47f913f2fab7ebc1934561ecb6ffb4afd/src/main/java/me/steinborn/krypton/mixin/shared/network/flushconsolidation/ThreadedAnvilChunkStorageMixin.java#L135-L149) from commit d24cb7e47f913f2fab7ebc1934561ecb6ffb4afd, I received the following result: (duplicate chunks underlined with unique colours) (note: for the test, I set `watchDistance` to `1`.)

image

For reference, here is the code that I executed:
```java
jshell> int watchDistance = 1
watchDistance ==> 1

jshell> for (int d = 0; d <= watchDistance; d++) {
   ...>     for (int curX = 0 - d - 1; curX <= 0 + d + 1; curX++) {
   ...>         ChunkPosition posTop = new ChunkPosition(curX, 0);
   ...>         ChunkPosition posBottom = new ChunkPosition(curX, 0 + d + 1);
   ...>         System.out.printf("pos top: %s, pos bottom: %s%n", posTop, posBottom);
   ...>     }
   ...>     for (int curZ = 0 - d - 1; curZ <= 0 + d + 1; ++curZ) {
   ...>         ChunkPosition posLeft = new ChunkPosition(0, curZ);
   ...>         ChunkPosition posRight = new ChunkPosition(0 + d + 1, curZ);
   ...>         System.out.printf("pos left: %s, pos right: %s%n", posLeft, posRight);
   ...>     }
   ...> }
```

This commit was introduced as a fix to #69, but it seems to introduce further issues.

Unless `sendWatchPackets` contains code to avoid sending duplicate chunks, several chunks are being sent multiple times. I also believe the number of duplicate chunks increases linearly as `watchDistance` increases. (Though, I could be incorrect as I did not spend a lot of time examining the code)

### PR DESCRIPTION
**Pull request by solonovamax**
This PR possibly fixes #70.

Previously, krypton was not sending any packets for chunk unloading, upon teleports.

The reason for this, is because `sendWatchPackets` was misunderstood to only send *new* chunks. However, it also sends chunk unload packets:
```java
if (!newWithinViewDistance && oldWithinViewDistance) {
    player.sendUnloadChunkPacket(pos);
}
```

Thus, it is important to loop through the old chunk positions & invoke `sendWatchPackets` on them, in order  to send the chunk unload packets.

This PR fixes that issue, as well as changes the chunk-sending order on player joins to send in a spiral, similar to teleports.

### CODE REVIEW

**Comment by andreasdc** [comment]
Interesting.

File: src/main/java/me/steinborn/krypton/mixin/shared/network/flushconsolidation/ThreadedAnvilChunkStorageMixin.java [hunk 1]
```diff
@@ -64,60 +101,124 @@ public void updatePosition(ServerPlayerEntity player) {
...
         }
-
+        
         ChunkSectionPos oldPos = player.getWatchedSection();
         ChunkSectionPos newPos = ChunkSectionPos.from(player);
         boolean isWatchingWorld = this.playerChunkWatchingManager.isWatchDisabled(player);
         boolean noChunkGen = this.doesNotGenerateChunks(player);
         boolean movedSections = !oldPos.equals(newPos);
-
+
```
Comment (astei) [inline src/main/java/me/steinborn/krypton/mixin/shared/network/flushconsolidation/ThreadedAnvilChunkStorageMixin.java:110]: Why the whitespace changes?

File: src/main/java/me/steinborn/krypton/mixin/shared/network/flushconsolidation/ThreadedAnvilChunkStorageMixin.java [hunk 2]
```diff
@@ -64,60 +101,124 @@ public void updatePosition(ServerPlayerEntity player) {
...
+    @Shadow
+    protected abstract boolean doesNotGenerateChunks(ServerPlayerEntity player);
+    
+    @Shadow
+    protected abstract ChunkSectionPos updateWatchedSection(ServerPlayerEntity serverPlayerEntity);
+    
+    /**
+     * Sends watch packets to the client in a spiral for a player which has *no* chunks loaded in the area.
+     *
+     * @author solonovamax
```
Comment (astei) [inline src/main/java/me/steinborn/krypton/mixin/shared/network/flushconsolidation/ThreadedAnvilChunkStorageMixin.java:177]: not really your code here (and not even mine), I'd just remove this

**Review by astei — CHANGES_REQUESTED** [review]
mostly formatting concerns here

File: src/main/java/me/steinborn/krypton/mixin/shared/network/flushconsolidation/ThreadedAnvilChunkStorageMixin.java (hunk 1 above)
Comment (solonovamax) [reply src/main/java/me/steinborn/krypton/mixin/shared/network/flushconsolidation/ThreadedAnvilChunkStorageMixin.java:110]: My bad, my custom formatting settings automatically add the whitespace. I'll remove it in ~30 (also, if you add a `.editorconfig` to the root directory, it'll have everyone else's code formatters match yours. Assuming you're using intellij)

File: src/main/java/me/steinborn/krypton/mixin/shared/network/flushconsolidation/ThreadedAnvilChunkStorageMixin.java (hunk 2 above)
Comment (solonovamax) [reply src/main/java/me/steinborn/krypton/mixin/shared/network/flushconsolidation/ThreadedAnvilChunkStorageMixin.java:177]: I added the javadoc for the method description, intellij added the `@author` automatically. I'll remove it.

**Comment by andreasdc** [comment]
How to get the jar?

**Comment by Kichura** [comment]
> How to get the jar?

Just compile krypton with "gradlew build" then look in build -> libs folder, easy.

**Comment by andreasdc** [comment]
> > How to get the jar?
> 
> Just compile krypton with "gradlew build" then look in build -> libs folder, easy.

Is the client-side mode affected or it will only help with servers?

**Comment by Kichura** [comment]
> > > How to get the jar?
> > 
> > 
> > Just compile krypton with "gradlew build" then look in build -> libs folder, easy.
> 
> Is the client-side mod affected or it will only help with servers?

See the [FAQ](https://github.com/astei/krypton/wiki/FAQ) for that.

**Comment by solonovamax** [comment]
@andreasdc this change will primarily affect servers.
The change still applies to singleplayer worlds, but will make minimal difference, as the connection between the internal mc server and the mc client is very fast.

**Comment by andreasdc** [comment]
> > > > How to get the jar?
> > > 
> > > 
> > > Just compile krypton with "gradlew build" then look in build -> libs folder, easy.
> > 
> > 
> > Is the client-side mod affected or it will only help with servers?
> 
> See the [FAQ](https://github.com/astei/krypton/wiki/FAQ) for that.

'edited this page on 6 Mar'
'commented 2 days ago'
Do you believe in coming back to the future?


> @andreasdc this change will primarily affect servers. The change still applies to singleplayer worlds, but will make minimal difference, as the connection between the internal mc server and the mc client is very fast.
> 
> I recommend you just use the latest version published on the [modrinth page](https://modrinth.com/mod/krypton/versions)

Right, I thought it will affect multiplayer, I don't have any issues with the latest commit so I will keep using that, thanks.

**Comment by solonovamax** [comment]
> 'edited this page on 6 Mar'
> 'commented 2 days ago'
> Do you believe in coming back to the future?

@andreasdc
This change does not affect the scope of Krypton. The FAQ page still applies.
